07-blueprints-and-jinja-2-templates/snakeeyes/app.py
from flask import Flask

from snakeeyes.blueprints.page import page


def create_app():
    """
    Create a Flask application using the app factory pattern.

    :return: Flask app
    """
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object('config.settings')
    app.config.from_pyfile('settings.py', silent=True)

# register app routes for page blueprint -- resides in blueprints/page
    app.register_blueprint(page)

    return app

07-blueprints-and-jinja-2-templates/snakeeyes/blueprints/page/__init__.py
# initialize blueprints
from snakeeyes.blueprints.page.views import page

07-blueprints-and-jinja-2-templates/snakeeyes/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

@page.route('/faq')
def faq():
    return render_template('page/faq.html')

07-blueprints-and-jinja-2-templates/snakeeyes/templates/layouts/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">
    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{{ url_for('page.home') }}">
            <img src="{{ url_for('static', filename='images/snake-eyes.jpg') }}"
                 class="img-responsive"
                 width="229" height="50" title="Snake Eyes" alt="Snake Eyes"/>
          </a>
        </div>
      </div>
    </nav>

    <main class="container">
      <div class="md-margin-top">{% block heading %}{% endblock %}</div>
      {% block body %}{% endblock %}
    </main>

    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">Snake Eyes &copy; 2016</li>
          <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
          <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
          <li><a href="{{ url_for('page.faq') }}">FAQ</a></li>
        </ul>
      </div>
    </footer>

    <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
  </body>
</html>